version: '3.1'

services:
  db2:
    image: ibmcom/db2
    privileged: true
    ports:
      - 50000:50000
    environment:
      DB2INST1_PASSWORD: password
      LICENSE: accept
      DBNAME: testdb
      instance_name: test
    command: db2start
    volumes:
      - ./database:/database